name: Java Servlet CI/CD Workflow

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

env:
  REGION: ${{ secrets.REGION }}
  ECS_CLUSTER: luckyweeky-ecs-cluster
  SERVICE_NAME: luckyweeky-service

jobs:
  build-and-deploy:
    name: Build and Deploy Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/luckyweeky-server:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/luckyweeky-server:latest

      - name: Register Task Definition
        run: |
          aws ecs register-task-definition --cli-input-json file://ecs-task-definition.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Update ECS Service
        run: |
          aws ecs update-service --cluster $ECS_CLUSTER --service $SERVICE_NAME --force-new-deployment --region ${{ secrets.REGION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
